spring:
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_cache?serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    host: 192.168.78.128
#    initialization-mode: always
#    type: com.alibaba.druid.pool.DruidDataSource

#\u5F00\u542F\u9A7C\u5CF0\u547D\u540D\u5339\u914D
mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      yws:
        mapper:
          debug

#debug: true
